language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: a0Mp6uuHBiwhyPRTKlXhQSNAuoDlhowcl8wAyFYsItOOzDqZneW3nY87P746eNuh20pUSiU3xMirZnBkzumWnru1GisxkeQxEwS8ITYYKX0NJMn01k6/ZyCbJSTSsZbRKVSPw6vwNUfos/ApOstTKDwIWuYvfZdJ+pdISZ4TeJUrfte73YRO9N9TMAX6e8qxT883SS1Q3bpNboZo5jxZU8puP+sFPvFpZXuuUWs+6ZN6gotookS4GxVg5K1hnCfuHxD0wGFzVXX6BCNiX7aTig8Es93hMlpDEMYftJaka/g72hqow2YRhVAkJw845wFSedevj/leBkcjJkwDDo9/8C7pG2vOahbZqeMG8hc+1iy+Ajtoc7sIinVdZ1BOh/d5Xe8BSoaJHcreQDMtXZlyDZfBijufC6NsQxVx6Ts8brwE4ryXiNgarql5bChgpszdi/2llHAculjcpxxOSMkgKrpEuCfwMmyiIh7UxYUYqjvzX57Ag95JpK29jYHuup+15Effy89sgnAMhYEZN4YQfxMwr/H0bMgb8ESfLlOT4b2ET4c3iBfXAJAspfnXUG2FEISE6dYDYvxop34gtZzc2LSrLOEaqYbewwZ4WmLVQMpNvIrjE9IldFcQsR6qOnhU++pbQI+ZMCbM9VIFS7dL0QDQtSVEDjDzQQ449cnlb2g=
  on:
    repo: FreeAllMedia/blunder
env:
  global:
  - secure: uM05fdus6GApXNR2+RDmjD7wpF9GBpxkEtiB+bTdSGW3m7IHVPU0OOzWRt/OZwE/OlxCqFBfhrI1/fy49wX3Q72qCf4Cl+yIbZoX4rFGW/fB2Y5OoH0D9w35mkYTH8tbU5GHZXjjbEaLxC+OgRA1kd7Pi2H/7XkIuuQh6zOqn8tIstpP1RweOydrtukAi+pS2nzBJ5SAfHLnyBpt8OIt27AgbW8dZZj5wbNIqSBRZhYmkVUTgiOvZ9HzFGHNvAK7aq9YN0L+luYsyT5zU+8XJtqUVYoOf37HY1UKpGqfCxIkjJaT0O2FexPeKSzpP5BgsGSwU1iDm23zS5WwZs0DCOJwaFX6YmatQcGzMOlpJluAUSmlwJH6TMetXQHerzXp4IeVGYeTh9UW1wPzXZYljM8vpiRuA586zT+3KPys6eF1pRblpvmeqMQszqm8nI4oSLefdvtxKXxh/XAIFMBgWEI9jeH8XGuqQQnMaMlfppCuRLc5IfHx/ncLvh/n0ScMnVtjmqpt4rJ0VqBSv+WQW0FQWpxyF09axCufoJOZZYIe4YCbkuhY8RKfds/1EFbDZSgb83uXcldYUa/QQkQiXXiYSX5RrlsW96iLZdzp/ePW6yw7hgtORn601WIrWgF5WDpg4zIEC0NOOaqJhVnPuroHEYYGwAZJSE8ZqaNkmWo=
  - secure: qnUERD4t+alllZA3cbFjN31sexPV00l7WLMhFEgDZjYLn6yIOE91JmH9dRk7OXU/C//kzU3W96WW/ecJDFcDpuSiMOdGYpaOLO0+KuDNgh4P0c/QkuXuZ09DYoZePn89M7CQts2YQvzhIe7XZT0Olqk0S3u6rp2MFWXTgSMFwWIm3MvJ4nI3Of/eMVHtjPrBQ6QkLirtPajbktDiQj4SiUTp73dWrjL6xkn+YxHkF84GeVtTsm1746DR4YdDnUm6ZX3a8F7GgLzGnGla+V06qK1J2Xfpk15YtDBRaqgotfNFT/Q+AYiriUkyWj7aSBr2joigKYWC6HNBW4aMS35ZTfdF1kzD2setxffZ6vc9rpO7dT+ixYKu4leX6ZOxFfCtF+dWx9pzjJrqQfGs/U6oxh5gJXOPojqNlqrFSSLdwvRTrMwSzhYv1s9KWlcNPsHfbPeGzh2fvtlm8WFB1aKkknOHHiyzmLUsmSOhJS/Q1/OoswjLBr3CKSDM7JDDTGQz/oF/9SzGMaF0GlSoBKa0IlN191Kwx1pjPD88VDNUhdB1KJotgC0dOWf5nO4nupXVUlP+s8Av9Nm44OPcisdeLRJyoSxfUZzgOg+55XG68mQf6GTan1eGpuQh94pxqWwUWCE+UyOX3G1DqUoVYqlPXU2FtoxIwQxqu0deqwKeCxU=
