language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  'on':
    tags: true
  api_key:
    - secure: saC5YX5fi5ym3OO25cfOWuqyPyuRyFnuTxUZ1+o/AbCIk++bsFIligBYjTrKJOAWSh14LVNofP9ZeqVJX1HxwSnCUaNU7RUt7cToKK8Ed8CzAr4nw3Xagp3JgXdSYK2kWX0YkGHmGoVYoKJ3aLlVReP1przLuVJxFpiWT9NHtquK+I7PzsnFHcKYJBw1B0AdZ9rKzk6D/AbF3v1Zo3ChH9SR2PAonCHukT4SQTUkdg85qWREGWk4asHi6dy0WspegXgCrW35deAJp6/OuLurCgp1ZS1hdw0HG6Z97gxGgLdUZmAMo8EFAoz/YQcrTPEFqGlcxUsWpzxgT+hx4CK0fjlP+bvY7a0loKzMurdAntvJwGg3vYzPO36fqQOl8Poh3yagkA9WKT5+86lPAot2HFgoQ1Le+A14WXlGY/WT8RywUyWhCyHQekrQ2jIgvistCBcjL90xGrk7avTeY9duk48lwMkHThPg//IrRUYabolaw4wvGhVmGQ4692CMc9V7g5FGfpd3cO/Bfm099FQF+5YJIGFLbYIIzkHsxb729Y621ndO2rKR8bfCFAri4gJ5eB+2ZfSw98U8F5290Y0eamiTz32E+oWKiHIDRIH1REwtsixswQFifTJmS9sbr6LydGsEGZ2tO3Lv6d1HkQPgMr+nb1ib/ToznQ3y0yHBqLI=
env:
  global:
    - secure: JZDxHB+H38woDpXp7QUlWcbDuOBKPv8LsKBaFM89KyMqeIdqZBxSZ0yEiyTfgX0esEwTuRGCzUJJAVP6W81u5Z9NyXVggje89BDmYU27aNodIcX3lemCoYz2ic2DOZSPcLyXPaIoxU6OqBXJ1Nqtg0h1a2jZV2fUXKpv1QPXFObuwFGjP2yMv/mDGr3ZM7bJ/1EX1ukseUckRthL1r+94G6BtYUmOnK0sx6bDA5KnZ+iG9rjVSigcwI+KFJOC8ldPKmeeDqSKMiRPoZX/X49T3WtQVyY8GRc31lt6CjUKva4MJqcRDuTjqHWPz7NvKZa2sGZ/C9t3ZPszIUxrMvimN6XmuMJP3B2jn5NZMT5ZBhI7p8p6vTKyvRaAZhYVwYG1loP+vk5Rrh0dBqu9Vo+rYt5zdtJ924910cuOzC1kJOkF0zuw+7l8iO4cufQju3Jxi4WPZHiV5873EHNqZzNlkREJPK8269UYG5InbM2w/j80uQ1yp/qU5qRIAZ1FOC5aZm7Fenv/qKVnCXd0WDbG3M7IHWRt45ZtGC+dbFCI3bl+TcDF80rNKTCI+dRN91kayPICQX2nnC6OWrlQXpspGpbNHs2O0IV4/HwtA3DGnFRDCMLz1G/+JnMkhQmHOehB3qJHRyV3erRjgsVut9ImiSce076KLQ4zKaVuZY/I9k=
    - secure: dQBogdIE5V/HrXw7ofvHQIT2cG/h5cvPEGwQoE0tOzWX4A0IVmRtUhMT0pHy5JMfCUNgNPfMlZxjH6BIOMAITFsoZWFoDD+5nkgWLV/XDamxdZBb9kch1gwt2zaduVLxNnwh1kCkD//w5lV8ZM+cIFLeRhy9uTnf8xI4TRrAwUYfEDFtaLU7kFSdIJ4/5IxAb+HoOIO92r+oSRn9wVUXdWmuyaZauVYgkT/vSr586PZK3CkXrW6e59aViXfd5eGmDmXqgO4hdt34IafNJvrFa9HJ2YicvYF1tUYtEaqrS0atVtEy3CgKZHR1CnlyrqfjWEwl/YrHjpPsd5IEVLhAWecC5co59BoDEF/9/IfGyt/sUCIwWD6kNCSaI0Ga+vBPHGshyKc3xPfKzRLLktYlvw0BI4cZzfonx4tbChVLoN2m6C2rEXnU+CCDGlEAg7226m0JZuTDCC0hSf3QZX2a2CI0bgH8eKApjZhSa68ftnJZvk0pYcrf/DySFkbpM1qpg5fF3xHCCF5xLRyJihfIklWvQlOL9z7X3gCQS1+jUUCg6S1Kb2kwe80p5OV4E6hXYs9eb2hNM2CtbaXxTwHwa5L3bjY3cRqvob0n4r//svcAacPmWesGZH0l6ZB5W1Ekw2E+H1BLc2XSTKOrJbdO7gE0oTsi/qmQpCoXBWmH+m4=
