language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  'on':
    branch: master
  api_key:
    - secure: WiC389JFwsTM9odOluCYyENGTqYkLMTGUW7ICAKmGW5n4hC+YaffvCB02uYQ+DCQVWNRIVGZClIY2A15f2b2wmZnRGDeZkiSGG1/PT1v5Dwqlg7jAIJIWcPyh0GCtY37bPX0kmlr0lMxkaPC87n2F9PYsMGwAHIc29RInUqCPw2++rgFyXuQdO9ZjIKU5iquiM0E4VZzxduARrinIFnFDC3F58d/w/zVUTwZWL4oKr7iniUqwUp8qlQ5GEqszDMlx/+/ZKSs1Il3FUCK8BmkvTwAZug4CRD9aKytRGTNmWsQwmDkp6TwGLjhC9FsAxddQ5wygvcWck2YqfxtGPBRFo0qVJriqRd0MDaE3yqSSkF/5Od3I43C/asycsLVsGmDHIWrSzrEIUDxplA0YLX5oSJZ6ucLMiJv6Oqz2jzym2MQrPyJyL69FYwUL1bqq1/L4Tl4jiRTYdvfqpTWwXfjPaJ9IRmIvUprH7f85Ac7nqkF7S6vfk02wgvQJVyRiNpegbPvl/4d/uEN00QvOTOhZO+mJOELKaMPc/JBesCDSsKSV5hUfWGdQG28Q1kZAUAGw6zXnK4b0XxRN34OznsMR74Fq1qJ8fZRak0CAy4I1cXwwfNihtEGMyoimhw364x7lSlGWQNd/1Yo//8HboYY7ouMszwf/4SwBUCM1XT7x/o=
env:
  global:
    - secure: uM05fdus6GApXNR2+RDmjD7wpF9GBpxkEtiB+bTdSGW3m7IHVPU0OOzWRt/OZwE/OlxCqFBfhrI1/fy49wX3Q72qCf4Cl+yIbZoX4rFGW/fB2Y5OoH0D9w35mkYTH8tbU5GHZXjjbEaLxC+OgRA1kd7Pi2H/7XkIuuQh6zOqn8tIstpP1RweOydrtukAi+pS2nzBJ5SAfHLnyBpt8OIt27AgbW8dZZj5wbNIqSBRZhYmkVUTgiOvZ9HzFGHNvAK7aq9YN0L+luYsyT5zU+8XJtqUVYoOf37HY1UKpGqfCxIkjJaT0O2FexPeKSzpP5BgsGSwU1iDm23zS5WwZs0DCOJwaFX6YmatQcGzMOlpJluAUSmlwJH6TMetXQHerzXp4IeVGYeTh9UW1wPzXZYljM8vpiRuA586zT+3KPys6eF1pRblpvmeqMQszqm8nI4oSLefdvtxKXxh/XAIFMBgWEI9jeH8XGuqQQnMaMlfppCuRLc5IfHx/ncLvh/n0ScMnVtjmqpt4rJ0VqBSv+WQW0FQWpxyF09axCufoJOZZYIe4YCbkuhY8RKfds/1EFbDZSgb83uXcldYUa/QQkQiXXiYSX5RrlsW96iLZdzp/ePW6yw7hgtORn601WIrWgF5WDpg4zIEC0NOOaqJhVnPuroHEYYGwAZJSE8ZqaNkmWo=
    - secure: qnUERD4t+alllZA3cbFjN31sexPV00l7WLMhFEgDZjYLn6yIOE91JmH9dRk7OXU/C//kzU3W96WW/ecJDFcDpuSiMOdGYpaOLO0+KuDNgh4P0c/QkuXuZ09DYoZePn89M7CQts2YQvzhIe7XZT0Olqk0S3u6rp2MFWXTgSMFwWIm3MvJ4nI3Of/eMVHtjPrBQ6QkLirtPajbktDiQj4SiUTp73dWrjL6xkn+YxHkF84GeVtTsm1746DR4YdDnUm6ZX3a8F7GgLzGnGla+V06qK1J2Xfpk15YtDBRaqgotfNFT/Q+AYiriUkyWj7aSBr2joigKYWC6HNBW4aMS35ZTfdF1kzD2setxffZ6vc9rpO7dT+ixYKu4leX6ZOxFfCtF+dWx9pzjJrqQfGs/U6oxh5gJXOPojqNlqrFSSLdwvRTrMwSzhYv1s9KWlcNPsHfbPeGzh2fvtlm8WFB1aKkknOHHiyzmLUsmSOhJS/Q1/OoswjLBr3CKSDM7JDDTGQz/oF/9SzGMaF0GlSoBKa0IlN191Kwx1pjPD88VDNUhdB1KJotgC0dOWf5nO4nupXVUlP+s8Av9Nm44OPcisdeLRJyoSxfUZzgOg+55XG68mQf6GTan1eGpuQh94pxqWwUWCE+UyOX3G1DqUoVYqlPXU2FtoxIwQxqu0deqwKeCxU=
