language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: XL7NqAPnRWs228Z5VVHRh51I3e50wCCMu97Cuzhm6q1JBgmgtnrt8//rVnUJJRwADLbwLlKVS8nbM0uatnalsslB+Q8NJaUrC2hM/bXXz1ozkxolLXeLXfPpvvPL5Kdj05oF+ztkOf81UGy03MiWM3pMbW4duPCGiJSr0GszlPBuDDNAX/LcUbDPJ2/JgwVp6Kp2JkwnaVuhYX7ZZdGCuJHbMfTnmXpUGzocK8kWE/BOhw8Y3QAuBi8Lh64GqUkwHOudaXyErIsLepBIKJ+cyEQSrNwawGlIY0A9Q15trAbF0us90WE3hJYtCsBPYILNnVbl0nPrkdehjwJuz9f6dgw957djz2Act7VOm+4FWEQfSOo8AR2g074+5vZydVfqc2B04qkF6/OvfBoYuZfbYehVc+so/AFZ4fVEFdye2omArB7ppwDH9iGLllpg10DPdv82nWqtUcSXBoU51eEUUiTBS2bQMMmLQ/RYym4pwA0Mde2k2hjS92XKk08D9lyanFcettA9WGEdunvQnU+7LDDYEVm/Wy/WicoUYcQGgfsgYff0UkDK+tp7Ef3EhWCBEml+977AM4z1VPNAHvhwlUOUvhUKAnrvanNycdaf+/IDGQvvcQZfjyznb+KRNRN4CoHuy4nMei3z0JtaL79JaIjaMAgeTMkYaAIJN5PAQfw=
  on:
    repo: FreeAllMedia/blunder
    branch: master
env:
  global:
  - secure: ODSAZEbb4y/iXNDNox5azYGedV+pFru81KHF4HfOqLpU/Hhk6BzVHgvA//KaZ5UnROZMZo/dEki/AizFTdTODN11owZz1ySuHwTCsZB0c6WXqyQpQ9BrpqukF/84du5TcaMpRyPh2IsUmYX/+yDzurjRzcoRkY1mrxuWrnQFrElIDFgJ6Xhy29/MZdUIANPU4YcwXys2dAEDv032DD5xEKmpCwBobxz2i1MjNLjgbnnMFejbrcNEJXNZwRjJYy/b44+z+dR/EDCBWCn4NRsIOrcEwsY0mLvDvl+Zq0bj+WuxHRRL8YvvQ2qigbGPm+DIWVlAC1cD1s/dmBD6m6oXPEx5qx83pUKRs2hE7/CS5FLP5X3vuR2tWQajUoO+68FsD7ertC8SriRv4kknBljZ+k2OFK3CnmQmaI6Lo3g9StnwAzx8bEfjuVmHGipBgpH/oI+N9mlOdqlPHSRJOti7AozlnqhO6xjIma2ogHx86elQjYkin1tDvgqEcj/eOPpi4RkTv236y6YZ7kezIy6Oi4kcY7AE3j4bmi9xTB1NyAE4gZx6Jhm+3/eyECNYAiCUgOBEAJJrV2+ZlxD/n4rfh/5sqPc58y3zBs1Pk9eqg0GWOiEovW4yswjNPiL9BeI8jbXKR+VAcxhrcQ8Nnv74ZVP+uBbluMki155z1jiIeJ8=
  - secure: VwK0JBld0rv96o37R6WYRALLoBbDvKa8+eJ0L3vvRJhB28Z285uzv90Qx62oUhQmA1bmRqB1I49zWmSXRmzSh9LzUB3JWZ+vjfuDpiNByym7NuTKC8FAqjo97Uux6Gik2ldH5bI9yiOuHzxd9B4fEs6waUdDN5DSrxb++V0D1TLg6WtFEMyGC/MnTVmjlfRLXc3Hyef7E0qVIbpTnSAr15PWDY3VHDMuLXp6V+ILLrKHL/F6sI0dB8f25s55bZP5HFmmbN1cHkorVR0XHxidQpjKL7JUMmdXUwdRPUVOy99RPoYA5eTSYFNKQjmH3X0ilGSwM7BDTrM3C+RJku5ZaylnKT3b3njRJA+pgiC3B+XAhrxlwg7zO62USA7FK5r71H+ai7tRBY/kFsb1U3iWp6tVuSBRAoQJwgnWdfHPGZ/H3uacfVaTJJc5eNBu+QWWysm4piHEUHPBjUsvmXguktyBgdJf8HNhgjeWzaT7MMUi7j1ujKMMKrqsbkGdYpmHf7Jc01N0zUnTlQ0TNmk48Re7vRh1Tq2w/bKhErXdAoc9kFqrQVKRFgSzXZzYEbjDVLexEYwpNwQmoufFbFGPrq3yqoK1K/OCRwf/jQxeqPZPCj0s372HhFV4ugoFBl733XSw8gcD3rFdAVy2NholrBOiHmtWCJ93cna6gSb7yxQ=
