language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  on:
    branch: master
  api_key:
    secure: ZrcOggdANrhqH24p7HK8LKeU3MlMlQW4RPzDw84aypbzEh46USvdKQfG4iDKOs6lCayVZdjwS4kTMCmRkMiYLLJEehdZ1p9OkPoDNNqym/lMNBMppE99HlPokubJz0SQ5YmYX2Y7xEFNjj79Ud3lUSf0lq2CaACUGxB7JQp3f0XIDoIX7eGwFfQr3ewUsFPtKMM7SmzasPbq4xeuGSwAFqIUCiI+igwkqpRd7pLJR97KLKrvXypY/Hj4XbXcZtu2c50vXJ8WttKSZWFcxvo6YzumpEMKcFWANlQs/+GRc47ni2mAzvR4n/MYfR//oS+61GpeGIIGnmZrJFi04m58hdaAxKt6It49IRBWlGyfArZZSvlR8eejgZn0kSE27fANEH+ajQ8DJJqHMTfh+TTZCBNbmXq2wCA0MlBDSfqSuCtHqrONZ7eFMt8BBgNE6AoYM2DqCrJcLCzM/TzM57YwYEnpNWKcSgFV/USpzIJ1kMdmQp9QU6PUodMHYImiDR96hCbc78hzpv9+ZIPwJEIZZ/5mPjVO5hL5GjFjZ5CE9a1vY5gWpEXHc3JXIekPutF0sJmj70o0RLvpE9MW3X/06hygZdTUdRW0PPTaeBWD1pb87I52/Qz5j71mxPabJC4txT3YtsGDfjeTgpVimiFBMGxRgc5CAw4LJtRO/RWvzo4=
env:
  global:
  - secure: kFxJyxO/agnjRvsSfLzjKlUrxQ9NMJeWJRuVoJxJSDuPy/CpP4fgSaLJEWW63xukvoz062KWh1CiJP9atvTp1zHEKjj3ia/U+z5Dv/il5Syi5NCVbZTrGMnABNX3cjfQG8CmMqrWjl6Pgv1P3h2RENQmLPacgX0DXp8R4pkYJQKwi+GRvbRLXHmuq2v5SsXC3EQ4h9XKcG7aHEDVOiocS0Hm1eX0mU7MKXrBKAyvZ+GZ+PHAOD6QJV8YptCa5lbIuYJCLmnME913kQMLLk4mrJ9sKkYaVT3kZllz3w9saMVdMSqJr1WhT3GWC3WKoLQDHgOEpzzAyeZl8VYr6uTuzfSwhVQCkqIyT0UtElZPHMt0THI7NkyAssF91BeyOgZrOK/HvjSrT6cZzhIwmBhhG4mXw6wgi0oJDnrJcB16JpLsCFWik33sT1cNEdxysMii2QfRMhTvTXp0u0f/mYM1Rc6t3kdMRyZVAe+LIczv0N3hAbN2ylHt3pqdwkLFo7dbUvvDfOSfo+bCDfolHaAREZNWLdXYI43nkRoeSAKCamV7Yi2RP0LQwczUDYUpQz1i0MX4xSKqHXzm8cCC2HRt5077+0sgKWPQ4/xW4kttFwx3ZLMVHVhsivypN2PE6E77U4D/zWPAmcz9c5mOfQVQVHiRM1QDdrh2yA8xhJLOAas=
  - secure: RtBDtM2F8SOR+02/Ov1lxPpK7azVRxtSpXlgU/I56ugMwY853ACzo7MEwVfuYuyMLsrdXXGQg4FreelTQGtHrDaei7PDMOnsNqq5BcCn2fx8YeYNyDACiRY7MUiA5Ryd5e7pL9r/rvKtTpxOGnjIKrAeDR1r2TudSl3+FhEQhA/K2CnAFb5pkVZdntNPQGAi7QX72gFchqmqUQKDCxyK7zEcCV8wPta/k2GiIId/95iQzLh8v00u7ri8KoKQtOQ1Ny8U8XEwQc6IsKBDFV+9u6sqQDl1SdxOpvdqEjYdjnXdkUREvb4Wc9V2R1Xv/NdJQiHNKAyX6Sle4aZ93IEMi//mV+oSBEHLCB7bZxuN7kFqyeuUXQx6Z+a4VOMjo4w1v1Q8cZKHT8PmRuYE3of6e/hG1wHUDliZCsQ3mZBrcGkwibBi/BENaA8QvGaaXOEUlR5Uop2SYTBKBH59ct3g+c9ssITmKJrWL+wKrZejtgrn7OgjCeMke7qDDY9wnzcuNgeL7Qsr8jfhTum6aQ5g6KAGHXAD5sq5mb69barVsIcahPo9KWAIoMJqhdr2riaGGizc9B80uwuWGI7Lu8GMHKvlkCyH3leSv/GB0QdJL3ItHgeNQzo0dUxoLcliQjXOsNjOz4yCayuziUw8yhu5NeqrPAehcGKLRZaWcjsp9dk=
