language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  'on':
    branch: master
  api_key:
    - secure: GTCqyAkv3lPXh244ojyWelrX/Dnk6dRgdXJi+CRJeqIcj7+zy/H3c8dHLYQkwwWqcRKnRly2zgnA4lYifOkQM3XOctyWMo1GkB9r+G55RHoQsF9U29NLS7DQOsaHocjNvE3QxG0w3aJAqQTVx0sVKZQRTfkjcpIiLAQLdTwFSE6YATrXfsChL/2TKuICPfmOP5YiGS2n+j1e7xDAFb1dvqv9KJhVz2jGnDZ1uTLgN0aIr1kIQmkKJPIX+c46X/tc4WYJDrrslJZVM67ex2HIwMPhZ0OPNeSNTxvDSc61KJoEI5tdgWw/QUkiOD5qEQrNg0Fapz7Voyx32BTsSP0cuvSifDaQhjqG12mQDG6S7YYpADFuLoF9BmSUTSa/8Low2P/cDcefROihzVQQ7zoMed9GqnuiunsQkYDCUKo1XhfaJyvAyHObfyrR5CkCzkMkiMh46fZSMoqguKiWWwfs9pE0i8XjenzUJ5FqQ890xe7cHTwpO7pThZpLkcX5HxXWfhDh8JvfNuukHPbu1dUaCj0IMFTJWH1SdZfysWX+qZ5yBulkD5CmP4Wfp+xP8Gkf9gZLuBCj3RpwLccLrfM3LwVW6wUAzZe6rVZu0PVXD1NgiWGeCud9vJ2mocPibgVTzn0wTpB8z31HvhRloZSk/hgSSFgIuFj7fwXoxyVJ85Q=
env:
  global:
    - secure: lec8GNoU1GSgBRrtUuZ0J8mYkbxzilrBCp1RrzE3mOKoEaRQms/9rYcDbgFzytt1gEE7vaUux4m5i+4Krevum/keHVE+gK/WcveDVqOm/BRcSPYFizUWfcEkqMLwT0ptRS5jJ2SsM1ZDDHfB6dQ+san4pEQY994c0bgHt2ghpcRqXUfPPyYKi7DdBEu7z1qBhXLKlknM018CJOs0NPNqtOpORypgioUKjK9RLJzEmkkmUEcJeMSGH2Xjm8vVvqV2RahG9mZUuy0fhXPbGr08Kn9B27HiT12Aol8n4cT+zViWHQKE86OLHlQf91noAqb5dXX8kf0TdwGMQaWx3vxDEUQe2bpanMgXzT/PL2amjKV943me8uwEJG9zsCiMgkvbMcWFuekRnfMFE7hvbYrLzXBLWMmgNpUoljxGpsu44L57zaowJDAhRJCWQAfCmC95Q3I6lRllHk64rivAUc6+BqHK5C32mVxl9x/Z7lWIZntlCJnXhFv8ssSrfntIzVzZJXKVWpt79nOUKmgAfZtBNj1cXivmrNTxZFXE4Q8VqIDE8Mhb/XalDeDjUCzQSbAmxa+nu+GgAUoiz/O3cM5/Wry6JV8llcBXyTv05zAOrLrpF5IvnH0Dcsl3KT3uZkutOgmhb/OLOG1hMDOX3D6Fh1wXt3M4EQoEy7SJ5iNIXdE=
    - secure: YEKuv1NlQQlorfVE8UHiMFINitZKJLVFvUnSoYKxdXuXMXi0b8kQzuZfpo1IvVT1z1hcuV5f8RxqB2U57EwETkoFc1AJi6pWQP5rfVpkBfRcitSIBe7gC+YjHBsjA1pCZnB0YvPsWfdWuvYdOYAg6D+gu5fPGSdIkoNQhi860DljUQhFNimBlgALNlZ5KophTcJKDD2oGHr/k4z3z3pPfIUvbogPSCEAOk6pSUtIv4AWQHZD9VjZuq6T6fx/xA8QjsiwizG+pPnWKLxO5OheMaBEev60SWFeNgsgXMtqmeeFVMg/2pieKDaGC2+u1DIHTJ8NBB8Oy/JPgxRwzqhc1xNa+H9mXgq/359habkFvfddn4BJcTj0nIQC/7PuR/XpPErL/XGF+tOwLdyf5/DEFu62quA3Bj85pcBLvTLLB8sdbTLCBk9byT5+M3RA0RMzK+hdx0ahpn7RtgqI0xcOiKE/xTwoMi243NTcHQqW+S2s8qzp/pQXCK4MbTpBJh0ER2Oiti1qvVuAYhNWWsfHLTSGdaASVwBKLyQK+WrgaRUqJDkWc9tiUlb17sEVGed+dJ8staJ0PWUKd9Z8uzLC8V6fXes2C286dvTjqBYV2cXnvupwQfE7QV7XrTVd42JaShsFmlzMWOH2r/FGj85yZxzpYHYBBIYlR8+hCTRTL3E=
