language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key: 'e9fcd073-116d-4f7c-9303-740b11a6f61d[object Object]'
  'on':
    branch: master
env:
  global:
    - secure: Qksy3fDmWSR/vtnFg6Uqo+w8ttfSyt5xqH+QY4JVe1y/tylGXb3mDQjnnuMZYL2Gx/5HSL6lrsPyBC5h2Ct50v20lm7faWdanHGsx1utqwN1TECCqj6MqK/Eq8sN6O7sZb2Y9lcHvgtSjrMwXH07yWzUB0R32sjEQuBu6xXGeT92aqRgGfzKjGLQ19dkNW53uLgtnHg+TbanKHUnTfUllIibsOD58ymBWJjr89PACgo1sy3Mj8FgTXPJaKlI9BV74qXPpRjvlIXkyJ3FLhcxM1cv+wT+Qeg8wJn940iK9TuZ0ptzhPFsSWwYugUluRXaPyxHJBNFK3epGyfeAnwAqDFLWHj8+41lOyiynAUlZlpwSicvyYuKfllWVkOUhHeAqB7Xoh2T9ZtvNCOIo3kky6VwPDEUbCQaETj+4r/kDoFdWJjxMI5Dw2gvIXppnaNdse41vARxqHskxT4wlksfnAqyOSzs1vrlDsbs6ha0uz7+ajyIcmiZhJRzWwKf0bg1EKk79WjFUyUsWJLddkJBwVsJtyEPjO9gtUgaOhOBn5atmetIZxfi+Kkdkus44Vof5SJ8Kd5wh0h69bT2us6XR6JOdC5mLZMXpdepGCa7utwIBgnvzWRlDjEshowO7E7HkE1VCk1Zlf8Q/MfhG1wIHudTTQ33ByhUltv9sP+C57U=
    - secure: EattJ+0FiX/KwR2ymC9LWdgM0hy7uGS7/kYUW4rA4uJXN+eNd2cgc/Gvw3wwQ0SXefzkq+FUX+0hdfMKopihGZdu3jMOTh1Zzw88xBI0E/5Sz8K4xQzpxJHZ31T3+X7ZOltLLiDoXq+EN/T386pgJXMdB0xVYdl6a7RugMkYRo5MEm28ja38tEAaiuR5FYIsry4NYT92otrjQcCtHlLZDJY6lw+41iwzRNEEdMYdX/XNqVi34stwwnotIb+1JRMjT/2WS/EItnl7LJNzoIJtvROlkXgHeyFS82pNviM7mw+k1D+S3Tpf0IkZeSJbxcKyDhQe6wpOnTWe5te38yDsej5rM3K/YeDMaEd5G4gZ6xDCR6PINQEd6Max5rT+KMNxsrRzxmAB5+XHeoJkYMzcyBBjDDJ9Vq7p1gb0UsIRVFALuT4uNWvJqyt8W3q5XoHSIXz0spDwIODkuX8Jq2HNqa7FtHr1XFoftgKA6SuOxsV1zTJWEDeHBbr1kf8Mp2NlGlCT7+zGvwOqjL/kaPLUOzOsh/AfxDm7i6rP3Hk/duZDvsuwuR/nK4J4Gb984Js9nNv4IM7qOF10z40K2JIbAosygXKi8Cd6AwUe9CaoPM2C56NaRurndJkHDmjI/ZDGs0XrdQEP9dNs3oItU/aASrxXB2lw5ufUtmQXcGMKiDI=
