language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  'on':
    branch: master
  api_key:
    - secure: g3S6Y8VX/esdFU1m5Y/rM6isnfZ+etFdWJ6nMxqP1i24IusV6UNZO+R/cucu4jRSkR+TUvqv4wXc/28jvhjCbBuIv7j52tAugyeYRvKsuxZkX/NNgDLuO4/UnlKuJ6djLDCtlZp8EEi9weg383Owhx0O4Bm7J6dtwDjFyhOeZgNxSD2LL/j6WpMrSE6eddkYw604vaTu9SUTDlnXgd5fOUN4GnrQQ1e6VixX3CfyoIeABbALVASiYQqUUMhkUISZjweAvK4XA5yMq2fW+hKB/iWQ6T6VSobNzWMmfTq0k+//QA4IHKMfWjrkLrysVAYvJ1FNf9ak/P9f1USPllfNQpRf7Z8tyA9L3k412tG7xtZWPgVDwkwjKM8wRfHiEdjF+wW9C5ADMPdHVP2jEuv4z4lcmgh4QUlD2yfBZvUlP30sW+JcGVk8wIX/QaqPJ8lA8sAVP595QwAi8UWL3ZLAjn3qzRCNZn/ODzcANfkCCV4qprJbub3Sq50o1VfZ4ruDL6bytD/KOTSXaNiMP+SkWE0MPlHuR94DvAuSgqO5awbk7Ih77HQOsGqnyYXVppqaeXlwQ1JCyfXPX1CC+g52i1uuoIdfZkz/0j4Ab5rkKgG7kIdcZUu/LuNyBIArm8fLWtpvHl34yTyV7gazHAfSUzWxJ6trDM6SHYZEQv6ERx8=
env:
  global:
    - secure: epDcrLsVLjIi125hfNJGIjk6qAZQYZuHRhyN4a7NXfGIPkk7fK52BAWzYuLW/l2YVLPX1pRgRk6LE5idEHdyDT/JoHNS9i7FZK/AQtikbWotySqBmrRCN4E/l383aDsLrD+vWTTOj5gu5woftlLw/9apC3DFcefWUBUDi7jr6LWn/2zCqSw9zrJD+svNM/oVKvshkhQIfwmpqdZGV19ydiEyCHUBUI9w1DHboYyWF5BCZ/dNuY+KqrNtjZUv6ehaoxpJQ9kgTCvgGhkCKngNX3vYxndEyJtqIj9Eay39nuROnV2HqKEAZccRtaAMifZsUwUMxpHUFSmRDexDvSLub2uRdMGEtChQdbIAnR7BA3IJU4oi8O6X8/gOFyIbNJG/yOFMFv62vq9Dz0ivJL9ssdrRVgCTjlwFAgmEjSvW54xYkma0pOsuNPatW0c5xdIGQPO9jApUydIQIlpkMqh24LgKZ9Zvc/BlWcvkJoZ19zd6NLvakPWmfXq5268oEy0nM4abMEh6bnjPBId5B9cpj87sFOXys6TwfTDbCIx0+4bilSgFNSQDmhqbUyC0X8iV2q8o7r/YYOhX3JHZQrJqBISDNiD+Ac0IuhInXPZuuPGsWmYmJqWN8SOf2namEQZAArLgPgZn6sjUKybjhhY+ZNxM0W1U4kg5s8KQvJ8NDRc=
    - secure: c4OiLRFRSO62dGHSTwhomG40WUenXmYnVnJ/I2W7pWeFzEUKh5TrKcOqCJftGJufvr9/lMOJLK/lWJs2o6xeRvZz+xccVRga2szTN2P82dixUXM4qmg7BzIkFFcNbNA6IqeQA95pv0iXsOdnwCe7blLjQDuVUiXKJJRrHq86kONSSUUWNvGrUEph8QN9fBqa54++g2eLdmFwLAG/EwPQA3aIRElHi7dYkRXb8Uh62pu3kZc6NKiCpGM0VwchPyAnAe5AeIHOmBb20hfJXU5pYxX5TILGvEn7oghPh4tiuAi6UdsZicWCaw6WbpF4qgH/bu0vsNCWlOFnQehicAa4LeR/Wsjo5oHyVqzdB7IdpBELBLGaufbqX51fv6yaWxgDY9zRpNOhCq4o6xqBIsTsLmL+e5Ko7cMuIsWMQvu5dqHBuVhBCCyvJzPFXqa98qBidV7wcwsglNLXB5rbm2CBCS2RtVx419gnEc2stBVDUs/5rFnUkxfU5u4t74i3gy/jo4xop7Az9pVHV4GPvqC0Bss9Kngux3zwvegzg3AhUr5nCvkcs6knfvx/76HbQEXFg8u1GCfY+gBL+8YzpyoCpEfyBDvxJB0On+A2JU/VQxqyvJ0gNtJl4zCSSXHWMDE31So1yA5geTMrHPG9CQCg+eQLNJvkewUv80zi+glThNk=
