language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: ICDGHsn84CcmwNgfEYzkWJWGE0ig0jVr3v+9DL4kB4vlf8WDCKUc1Hj3aPRQHnqm4nhWWiWHwnmWSFVdIw5zbN16N935+R6sPZzytacaU3LLpsuMCVIRWHOopaS3WgwOq1x8TFIyb6AiUeb3qPuk1ZL8HvixdogvyVM7PFE8FcclTgZpozGsVPVNVgPKmCl9V+yIxwLr6DiEuMMgRrk9Ix5pl0JM6gsfkaNwsXAQV6YJqt0ica/6D+3corizUC3MkfJql+6I9g2tyCRBIRkeYe402epQwac8WPlzNlcAPCfReq69TLY5hZwvcukuY7FvYfI0CPMeerizrmgPARG+7xS7mFO59fl+sQgGANk+xnNa0D2Dj9IYY4eUBzMyUeLu0mMb8x664cBkkQ5xKq/MJZ0mVtHa+RmFeazcmnmsTthbm1hn8BbWwfPcQb7lUWsGE66B8Oe1XAsTThvknaYDBdOVkwHamnto5Cp9H2SOlujJK+9R4/D2KhyxSuc3tSiCwtPJPAHH8dbacTabHFB4TC6NTTkKysxkpxI9KCxW1TKRdrneB263r7p23GnEEadLO6HkQuOB+S0pN9FTe5IpBlIpRUupf1u1lcIg239/IkA0swRXtKjuoOTEKjUcmn1nX0bMwEJF2ZlJOfZ+5KovNaVxwkWhlJt/ISHshuN1dNc=
  on:
    branch: master
env:
  global:
  - secure: o6Fdvbtz6uwEx37BxFfD6g04zZYHRW+ad2xbdBNgGrBudTl11SAoJ3DWp4WbnkTLnSynhlwlRktPQEf83cV66t5zG+PUfnBqhpXrCIjjxQEFtO7P+82xApGuuf+rIbIOkI0CzrvU75xeuKXWXzfG6Kz0Qr/y9g7TS2KvE1fHQ9D6xfjH8KkOKjD9pwgkFphhLGDdH+a2/UwXSJRBDf5SKXuCvjXOsyqunIjBDVVWUYf+aJigpKh9JSByUycH1HK/V5ANDFAySPHpdWIUlnu/aaaEcp0fusW0vKqYSfEDC8O+HUgdLUxNsHlMw2t7laSo0LVBUBQ3OM3AIHBf2Jurxrp6pP66eLQhsMm7Y8UbDUUQv/XMW3oovugyQ4N/K5khDpJyMN9l8sNkmb9ijr0hTxtw8tAk/kdb8k5JbggQWyVJT+QOsZPSu4wpCfTZDEVnAwEcTTIHMIH5FF8vB+X//1JHBE/c2SmbGsoF3TycEAKwy8qKxRQ+UmCeKAHQpY5Vc44i+1t6KQso6LeAm/2DXnRbE9B40r4NHMlZGH9WduPA9/Vo+2Bx+Mf/RbzdQian6nUEok9CiDlXWW0lg+02xciOdOAjatuvluOMTIl/HIXD3UkcQTf6Lzzup0vw/D7Or5/edPtwJYEzJSWEeMKhTCxtMvaeXDI/bOdxpDgxL+0=
  - secure: DZno7qakEdECgs0LVsyeIn0GAHfRPDt9SDUHde5u3BXyl1tYQJE6VPZxiyBUdmxd0QUe+mcqCOfmB4Obfnp3FXMDFX5U3XeJpOTTXpD0eJjeLRqeLj+cb4ruXiVyuw2wjaHtTDElFOJieCYVIN+RKVH/Nx7quJqEIFdXFN4c1Mhu/ECiAh1VZX7l50/4CGvTB/TVF0Q3A4nNzDnXKIbm9MNOtRHEUXN08s9yxMKOAP3VMm0DPPZsYvYH1JfYS9/0Oud6n/TkSFstV4QKSHKdCtQxCChtKxzAMwDJngjLQ3U2qjlUTDDAr8b+eH9sPmNZmKlBzX6/sdBBI9H7cJLEC/MsoJbvPLwGworAtvvpHvfx2BnTbZXpo7AFEjzIjxnsg/0NkU+zNY9y/MOB2RsswUknf5bc0gWGAuoKy/BUppGezyClksAaOy8y9ClusR8YXgYGmQPXVjfj5b+8fDYHR/8A5Mgonu0ywvshXBQZ7Uv/Qr61hPH3NS4tkzGrSVfLEHALK26BnWfOLQbPSFhVIB/j1myxFiBAsz/OQkdex6a5iQrSKr9phEFXULb5BQcf9xRsMDsreRhHR2dj/V1pveyrx+mlev20r8LI2p6etJog85yMOao15FZq0moOoYQThdWuGELNt/X+877XkbtWhzVNdBW/r/rs2SIQ421PXng=
