language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    - secure: T90gdNmuAERSoYdPA7Juzd/e5f6z6QMlh2Jd5+gLIACviwFzk+DKdhHucwY5mi+asIgW4k3XYjjYsve9ozn+G/1Sz4/G0X0DnQgzqnZBtejXz223WQf8UFrdU4Q19CACLQkKI5Hf3XTz1y7x9ZX+COS52BDsnlyeBfabR/zgqK2OU2pKWut9a4IjcsnOC9Kq8IJT5IIWfEo0XH2JKL8XRwh1lxoLRZaSp/msJgcb/e3uEA3CAm49Gz6teZp/WTomslD7mbMPKk142c4OhJX7SnnPx5ehuztWnq/fr2IALriovuu2s7sfqjCA1G7fUSM2MTAIG1X72tc1AzQzJlv3ybRRJ+p2E1J4IDo1F85ynjR7uf2bveRBXgUrP553IbYTdoN9F9MXKntq3hB80GhMCqNBLhIgk6dSvUiIH0KAtnggNnAebST142B+MBRlLAyaY8SOHLZPckeN1/UcrvT7/JiCqXezjyvOM814+O6tlzmQELppNervS2yXNJeox0A9qF0DuMqbp/0tkNnR5wQTHtQ1SFOxmvPWYH2H6x3OptCb+rsZGqEXfz58Wmpg24/ZgeoAp8F4txKbSZL3znieL9CAiEPl88LF982k0HSQtypJembFsViwkEDP55N/0bSBD6PXsdW02fzlISk2wazhrKfCtvyBR8Iaf7MHcICYe7g=
env:
  global:
    - secure: OzhQzFcxHreFWMS6yHAtTEl5x1nHbYjMKXBP7fpU6NOzfIpbLCa5bQxE+ZWYGsFujLcTCePmEKuSW0mBlBg+N7CjRHWv8Lb6ik8JvQdAPe5nDfoEqQ1hpCwUyNrEaiWfOMG60TqJGzUeJeTdfcXmQwxxSQLBuRjPw85J+418PrMSWpVG5p4B+Ma5NAGo00tT+mVReEpCpT1SxRdvtfoM2sjhMPWlrfIW5M8TeE/0z9+5EyII1Cl4MHNlGn2igNJgaMWbKRuiwztWXtqgw6D3m1O21tXQ4lmHtFme4yVlzNtOQ2fPwq4TovJM+GeHNKShbd73imM0TrApiK45p6/d34KSSw+g+4NjL1vMh6hjwgxPujljcgMPn3O8/P692te8OBWhe/c/eH4gj42xFqVcP3XftrLwOaRJnOx7ODnXkdLf8qLT9tiI5j7FtndT7HD/WvUIRGOOvbsAsZXIhJ+E5KX9XKKE3oML70WMZGH0R6wFUyw0hMa+Rhl/SeK4YUa17I6ohc/sjNDEXeRZaBwD8nDf2YljXam3+7sIybe3H9poVWL7xC0SGeKmzCP/dWBTnxn3QB/bpaku5WiNcvVWExrfOO8Q8EY9e/St7QfV9kML7D/esn+arTpA9j/3j/RDBl8c6BSlKQZdQDCBLJwhdkiHul+wkRRpZnXXrEk6CLM=
    - secure: n74fMWoUo5AcBOIVHDKDOyMFJJblhi/XEGcAk/jg3Hn6ozTLYq0/5iMbG+Ia5v7oCNeo18AnpwJEhOcJfePNS9TD71m2Qn74fpFFV3JYAQWWTsoePrJEREaMgJEQ+YDonygrOVAWUK40gD+bI/JjDcbH/9hfBHFyuXpireoJeK5PM3H/b5hDMR+QCxwt2fADWK18urQ/mAIz7bVCvfhISxniXy25F5Jvh41NfTDhbupZ1T8s9j+e2SycIyA/bc+qSZPIKytbFx7Wt9kEBdW9cWrDs/tCNrxdjNY7simmzFGhuzRh7+YLpvp5/Ijk/+rF4inYTuxc5cI04vT/GJ8xFmwYr17lBXdAZSErU36zuQFCAbWY35bHlk44m/PxylE9dOc6iTyQCwQtzmu6EUoTpOQ2S8xmpL6Z8c1vJMWFcBysNLpEbIAWVzbMFOuxTj9cdfF+bhPQa4u510eW9fTcq+Mqgcdy15NN4Ag8vNjJxE2cV5FKa5w81ncC6wXkS1KYfB6j+P6dNj03Uv0gXe0lAOy01muL99DRNXOsPWDOnWduhE+OdMrqd7VeXiHnV6g+pE/Mj9XlUZxcXjaYdonQ6ZGiMR9djxJe0dHgFKkaPghl/rCNP5QhRoTgJOacWgw04Ei5Ftv6hyP4ujMWu6uKBwxv7PqNpxYIOjvjE5g3q3I=
